# Generated by Django 5.1.3 on 2024-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adresa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_nasterii',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gen',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationalitate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ocupatie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
