# Generated by Django 5.1.3 on 2024-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0003_customuser_cod_customuser_email_confirmat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cod',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
