# Generated by Django 5.1.3 on 2024-12-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0005_vizualizare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descriere', models.TextField(blank=True)),
            ],
        ),
    ]
