# Generated by Django 5.1.3 on 2024-12-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0006_promotie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produs',
            options={'permissions': [('vizualizeaza_oferta', 'Poate vizualiza oferta speciala')]},
        ),
    ]
