# Generated by Django 5.1.3 on 2024-12-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0007_alter_produs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocat',
            field=models.BooleanField(default=False),
        ),
    ]
