# Generated by Django 5.1.3 on 2025-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0008_customuser_blocat'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='stoc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
