# Generated by Django 5.1.3 on 2025-01-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0011_remove_produs_stoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='stoc',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
